-- +goose Up
ALTER TABLE users ADD COLUMN IF NOT EXISTS online BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ;
-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS last_seen;
ALTER TABLE users DROP COLUMN IF EXISTS online;
